plugins {
    id 'java'
    id 'io.cloudflight.license-gradle-plugin'
    id 'com.gradle.plugin-publish' version "2.0.0"
}

description "Cloudflight Gradle Test"
group "io.cloudflight.gradle"
version "1.0.0"

plugins.forEach {
    logger.quiet("Plugin {} applied", it.class.name)
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.cloudflight.json:json-wrapper:0.3.3'
    implementation 'org.brotli:dec:0.1.2'

    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.1")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.8.1")
}

// TODO: remove after upgrading to autoconfigure 1.3.0
// ensures a JUnit version compatible with gradle 9.3 is used
test {
    useJUnitPlatform()
}
